name: GitHub Action
run-name: ${{ github.actor }} is building the repository 🚀
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container: 
      image: maishuji/dc-kos-image:16.2.0-06sep26
      options: --user root
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run:  |
          echo " 🫣 Building..."
          source /opt/toolchains/dc/kos/environ.sh
          cmake -S . -B build-dreamcast -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=toolchains/dreamcast.cmake
          cmake --build build-dreamcast --verbose
          echo " 👏 Build completed"
        shell: bash
